version: "3.8"

services:
  app:
    container_name: ha-super-shoplist-prod
    image: ha-super-shoplist-prod
    build:
      context: .
      target: production
      args:
        - REACT_APP_HASS_URL=${REACT_APP_HASS_URL}
        - REACT_APP_HASS_TOKEN=${REACT_APP_HASS_TOKEN}
    ports:
      - 3000:80
