version: "3.8"

services:
  app:
    container_name: ha-super-shoplist-dev
    image: ha-super-shoplist-dev
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - REACT_APP_HASS_URL=${REACT_APP_HASS_URL}
      - REACT_APP_HASS_TOKEN=${REACT_APP_HASS_TOKEN}
      - REACT_APP_PUBLIC_URL=${REACT_APP_PUBLIC_URL}